//
// Created by minau on 2/29/2024.
//

#ifndef SFML_PROJECT_DEFINITIONS_H
#define SFML_PROJECT_DEFINITIONS_H

#define SCREEN_WIDTH 768
#define SCREEN_HEIGHT 1136
#define SPLASH_TIME 3

#define X_PIECE 8
#define O_PIECE 0
#define EMPTY_PIECE -1
#define PLAYER_PIECE X_PIECE
#define AI_PIECE O_PIECE

#define STATE_PLAYING 98
#define STATE_PAUSED 97
#define STATE_WON 96
#define STATE_LOSE 95
#define STATE_PLACING_PIECE 94
#define STATE_AI_PLAYING 93
#define STATE_DRAW 92

#endif //SFML_PROJECT_DEFINITIONS_H
