//
// Created by minau on 2/29/2024.
//

#ifndef SFML_PROJECT_TEXTUREENUM_H
#define SFML_PROJECT_TEXTUREENUM_H

enum textureEnum
{
    SPLASH,
    BACKGROUND,
    CIRCLE,
    CIRCLE_WIN,
    CROSS,
    CROSS_WIN,
    HOME,
    GRID,
    GAME_TITLE,
    PAUSE_BACKGROUND,
    PAUSE_BUTTON,
    PAUSE_WINDOW,
    PLAY_BUTTON,
    PLAY_BUTTON_OUTER,
    RESUME_BUTTON,
    RETRY_BUTTON,
    SOUND_OFF,
    SOUND_ON,
    EMPTY
};
#endif //SFML_PROJECT_TEXTUREENUM_H
